"""
Example file showing how to use autogenerated petstore api client.

You can run this file via python -m example.petstore_example
"""
from example.petstore.apis.pet.addPet import Pet
from example.petstore.apis.user.createUser import User
from swagger_codegen.api.adapter.requests import RequestsAdapter
from swagger_codegen.api.configuration import Configuration

from .petstore.client import new_client

if __name__ == "__main__":
    client = new_client(
        adapter=RequestsAdapter(debug=False),
        configuration=Configuration(host="https://petstore3.swagger.io",),
    )
    user = client.user.createUser(User(id=1, username="Test user"))
    assert user.id == 1
    assert user.username == "Test user"
    print(user)

    pet = client.pet.addPet(Pet(id=1, name="Pet", photoUrls=["http://my.url"]))
    assert pet.id == 1
    assert pet.name == "Pet"
    print(pet)
