"""
Example file showing how to use autogenerated petstore api client.

You can run this file via python -m example.petstore_example
"""
from swagger_codegen.api.adapter.requests import RequestsAdapter
from swagger_codegen.api.configuration import Configuration

from .petstore.client import new_client

if __name__ == "__main__":
    client = new_client(
        adapter=RequestsAdapter(debug=False),
        configuration=Configuration(
            host="https://petstore3.swagger.io",
        ),
    )

    pets = client.pet.findPetsByStatus()
    pets = sorted(pets, key=lambda pet: pet.id)[:5]

    for pet in pets:
        print(f"id: {pet.id}, name: {pet.name}")
