from dataclasses import dataclass
from swagger_codegen.api.client import ApiClient
from swagger_codegen.api.configuration import Configuration
from swagger_codegen.api.adapter.base import HttpClientAdapter


from .apis.pet.api import PetApi

from .apis.store.api import StoreApi

from .apis.user.api import UserApi


@dataclass
class AutogeneratedApiClient:
    configuration: Configuration
    client: ApiClient
    pet: PetApi
    store: StoreApi
    user: UserApi


def new_client(
    adapter: HttpClientAdapter, configuration: Configuration
) -> AutogeneratedApiClient:
    client = ApiClient(configuration=configuration, adapter=adapter)
    return AutogeneratedApiClient(
        configuration,
        client=client,
        pet=PetApi(client),
        store=StoreApi(client),
        user=UserApi(client),
    )
